EXEC sp_InsertEmployee
    @EmployeeName = 'Sakshi Bahirat',
    @Fk_BranchId = 1,
    @Address = 'Pune, MH',
    @Mobile = '9876543210',
    @SkypeId = 'sakshi.skype',
    @CcEmail = 'cc@sakshi.com',
    @Fk_HeadDesignationId = 2,
    @JoinDate = '2023-05-10',
    @DutyHour = '09:00:00',
    @LeftCompany = 0,
    @LeftDate = NULL,
    @UserName = 'sakshi.b',
    @Password = 'secureHashedPassword',
    @AadharNumber = '123412341234',
    @EmployeeCode = 'EMP001',
    @Fk_DesignationId = 1,
    @Fk_DivisionId = 1,
    @Fk_LocationId = 1,
    @PinCode = 411001,
    @Email = 'sakshi@example.com',
    @BccEmail = 'bcc@sakshi.com',
    @PANNumber = 'ABCDE1234F',
    @Fk_GenderId = 1,
    @BirthDate = '1998-08-15',
    @Fk_ShiftId = 1,
    @Photo = NULL,
    @Signature = NULL,
    @Fk_EmployeeTypeId = 2,
    @LoginStatus = 'Active',
    @SignaturePath = 'Signatures/sakshi.png',
    @CreatedBy = 1001;


	SELECT * FROM Tbl_EmployeeMaster